version: '3.9'

services:
  mainservice:
    image: terraform-own-module
    network_mode: host
    working_dir: /infrastructure
    entrypoint: ["sh", "-c"]
    command: ["cd terraform && terraform init && terraform validate && terraform apply -auto-approve"]
